/* ============================================================
   AgroDirecto - Modelo de datos reducido (11 tablas)
   Motor: PostgreSQL

   Version PostgreSQL del script agrodirecto_schema.sql (SQL Server).
   Mismo modelo, mismas tablas, columnas, CHECK y restricciones;
   solo cambia la sintaxis propia del motor:
     IDENTITY(1,1) -> GENERATED BY DEFAULT AS IDENTITY
     DATETIME      -> TIMESTAMP        GETDATE() -> CURRENT_TIMESTAMP
     BIT           -> BOOLEAN          TINYINT   -> SMALLINT

   Antes de ejecutarlo, crear la base (fuera de este script) y
   conectarse a ella:
       CREATE DATABASE agrodirecto;
   ============================================================ */

/* ------------------------------------------------------------
   1. ROL
   ------------------------------------------------------------ */
CREATE TABLE rol (
    id_rol      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol  VARCHAR(20) NOT NULL UNIQUE
        CHECK (nombre_rol IN ('productor', 'transportista', 'administrador'))
);
-- Orden importante: 1 = productor, 2 = transportista, 3 = administrador
INSERT INTO rol (nombre_rol) VALUES ('productor'), ('transportista'), ('administrador');
/* ------------------------------------------------------------
   2. USUARIO
   Absorbe: productor, transportista, administrador y suscripcion.
   Las columnas propias de cada rol son NULL para los demas roles.
   ------------------------------------------------------------ */
CREATE TABLE usuario (
    id_usuario          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo     VARCHAR(120) NOT NULL,
    correo              VARCHAR(150) NOT NULL UNIQUE,
    contrasena          VARCHAR(255) NOT NULL,
    id_rol              INT NOT NULL,
    estado_cuenta       VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado_cuenta IN ('pendiente', 'verificado', 'bloqueado')),
    fecha_registro      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Datos de productor (HU-01)
    dni                 CHAR(8) NULL,
    distrito            VARCHAR(100) NULL,

    -- Datos de transportista (HU-01)
    ruc                 CHAR(11) NULL,
    placa               VARCHAR(10) NULL,
    capacidad_toneladas DECIMAL(6,2) NULL,
    licencia            VARCHAR(20) NULL,

    -- Datos de administrador (HU-16)
    ultimo_acceso       TIMESTAMP NULL,

    -- Plan premium (HU-21): es premium mientras premium_hasta > CURRENT_TIMESTAMP
    premium_hasta       TIMESTAMP NULL,

    CONSTRAINT fk_usuario_rol FOREIGN KEY (id_rol)
        REFERENCES rol(id_rol),

    -- Cada rol solo puede llenar sus propias columnas
    CONSTRAINT ck_usuario_datos_por_rol CHECK (
        (id_rol = 1 AND dni IS NOT NULL AND distrito IS NOT NULL
                    AND ruc IS NULL AND placa IS NULL AND capacidad_toneladas IS NULL)
     OR (id_rol = 2 AND ruc IS NOT NULL AND placa IS NOT NULL AND capacidad_toneladas IS NOT NULL
                    AND dni IS NULL AND distrito IS NULL)
     OR (id_rol = 3 AND dni IS NULL AND distrito IS NULL
                    AND ruc IS NULL AND placa IS NULL AND capacidad_toneladas IS NULL)
    )
);
-- Indices unicos parciales: solo validan unicidad cuando la columna no es NULL
CREATE UNIQUE INDEX uq_usuario_dni   ON usuario(dni)   WHERE dni   IS NOT NULL;
CREATE UNIQUE INDEX uq_usuario_ruc   ON usuario(ruc)   WHERE ruc   IS NOT NULL;
CREATE UNIQUE INDEX uq_usuario_placa ON usuario(placa) WHERE placa IS NOT NULL;
/* ------------------------------------------------------------
   3. CULTIVO
   ------------------------------------------------------------ */
CREATE TABLE cultivo (
    id_cultivo      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_cultivo  VARCHAR(60) NOT NULL UNIQUE
);
INSERT INTO cultivo (nombre_cultivo)
VALUES ('Papa blanca'), ('Cebolla roja'), ('Zanahoria'), ('Maiz');
/* ------------------------------------------------------------
   4. LOTE
   Absorbe: viaje y transaccion (ambas eran relaciones 1:1 con lote).
   Los datos de viaje y de transaccion son NULL hasta que el lote
   se confirma / se entrega.
   NOTA: id_transportista queda en NO ACTION. Los usuarios se
   bloquean (estado_cuenta), no se eliminan.
   ------------------------------------------------------------ */
CREATE TABLE lote (
    id_lote             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_lote         VARCHAR(20) NOT NULL UNIQUE,
    id_transportista    INT NULL,
    estado_lote         VARCHAR(20) NOT NULL DEFAULT 'formandose'
        CHECK (estado_lote IN ('formandose', 'confirmado', 'en_transito',
                               'con_retraso', 'entregado', 'cancelado')),
    fecha_creacion      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Datos del viaje (antes tabla viaje)
    origen              VARCHAR(100) NULL,
    destino             VARCHAR(100) NULL,
    fecha_salida        TIMESTAMP NULL,
    fecha_llegada       TIMESTAMP NULL,
    flete_total         DECIMAL(10,2) NULL,

    -- Datos de la transaccion (antes tabla transaccion)
    porcentaje_comision DECIMAL(4,2) NULL,
    monto_comision      DECIMAL(10,2) NULL,
    monto_neto          DECIMAL(10,2) NULL,
    estado_pago         VARCHAR(20) NULL
        CHECK (estado_pago IN ('pendiente', 'pagado')),
    fecha_transaccion   TIMESTAMP NULL,

    CONSTRAINT ck_lote_fechas CHECK (fecha_llegada IS NULL OR fecha_salida IS NULL
                                     OR fecha_llegada >= fecha_salida),
    CONSTRAINT fk_lote_transportista FOREIGN KEY (id_transportista)
        REFERENCES usuario(id_usuario)
);
/* ------------------------------------------------------------
   5. CARGA
   id_productor ahora referencia directamente a usuario.
   ------------------------------------------------------------ */
CREATE TABLE carga (
    id_carga            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_carga        VARCHAR(20) NOT NULL UNIQUE,
    id_productor        INT NOT NULL,
    id_cultivo          INT NOT NULL,
    id_lote             INT NULL,
    peso_kg             DECIMAL(10,2) NOT NULL CHECK (peso_kg > 0),
    tipo_carga          VARCHAR(20) NOT NULL DEFAULT 'perecible'
        CHECK (tipo_carga IN ('perecible', 'seco')),
    direccion_destino   VARCHAR(150) NOT NULL,
    tarifa_propuesta    DECIMAL(10,2) NOT NULL CHECK (tarifa_propuesta > 0),
    fecha_recojo        DATE NOT NULL,
    es_urgente          BOOLEAN NOT NULL DEFAULT FALSE,
    estado_carga        VARCHAR(20) NOT NULL DEFAULT 'publicada'
        CHECK (estado_carga IN ('publicada', 'en_revision', 'confirmada_en_lote',
                                'en_transito', 'entregada', 'cancelada')),
    fecha_publicacion   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_carga_productor FOREIGN KEY (id_productor)
        REFERENCES usuario(id_usuario) ON DELETE CASCADE,
    CONSTRAINT fk_carga_cultivo FOREIGN KEY (id_cultivo)
        REFERENCES cultivo(id_cultivo) ON DELETE NO ACTION,
    CONSTRAINT fk_carga_lote FOREIGN KEY (id_lote)
        REFERENCES lote(id_lote) ON DELETE SET NULL
);
/* ------------------------------------------------------------
   6. SOLICITUD_CHAT (HU-06)
   Productor, transportista y administrador referencian a usuario.
   ------------------------------------------------------------ */
CREATE TABLE solicitud_chat (
    id_solicitud        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_productor        INT NOT NULL,
    id_transportista    INT NOT NULL,
    id_lote             INT NOT NULL,
    id_administrador    INT NULL,          -- quien aprobo/rechazo el chat
    estado_solicitud    VARCHAR(20) NOT NULL DEFAULT 'pendiente'
        CHECK (estado_solicitud IN ('pendiente', 'aprobado', 'rechazado')),
    fecha_solicitud     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_solicitud UNIQUE (id_productor, id_transportista, id_lote),
        CONSTRAINT fk_solicitud_productor FOREIGN KEY (id_productor)
        REFERENCES usuario(id_usuario),
    CONSTRAINT fk_solicitud_transportista FOREIGN KEY (id_transportista)
        REFERENCES usuario(id_usuario),
    CONSTRAINT fk_solicitud_administrador FOREIGN KEY (id_administrador)
        REFERENCES usuario(id_usuario),
    CONSTRAINT fk_solicitud_lote FOREIGN KEY (id_lote)
        REFERENCES lote(id_lote) ON DELETE CASCADE
);
/* ------------------------------------------------------------
   7. MENSAJE_CHAT (HU-06 / HU-18)
   ------------------------------------------------------------ */
CREATE TABLE mensaje_chat (
    id_mensaje          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_solicitud        INT NOT NULL,
    id_usuario_emisor   INT NOT NULL,
    contenido           VARCHAR(500) NOT NULL,
    fecha_envio         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mensaje_solicitud FOREIGN KEY (id_solicitud)
        REFERENCES solicitud_chat(id_solicitud) ON DELETE CASCADE,
    CONSTRAINT fk_mensaje_usuario FOREIGN KEY (id_usuario_emisor)
        REFERENCES usuario(id_usuario)
);
/* ------------------------------------------------------------
   8. CALIFICACION (HU-04)
   Antes apuntaba a viaje; ahora apunta a lote (el viaje es el lote).
   ------------------------------------------------------------ */
CREATE TABLE calificacion (
    id_calificacion     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote             INT NOT NULL,
    id_productor        INT NOT NULL,
    estrellas           SMALLINT NOT NULL CHECK (estrellas BETWEEN 1 AND 5),
    comentario          VARCHAR(500) NULL,
    recomienda          BOOLEAN NULL,
    fecha_calificacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_calificacion UNIQUE (id_lote, id_productor),
    CONSTRAINT fk_calificacion_lote FOREIGN KEY (id_lote)
        REFERENCES lote(id_lote) ON DELETE CASCADE,
    CONSTRAINT fk_calificacion_productor FOREIGN KEY (id_productor)
        REFERENCES usuario(id_usuario)
);
/* ------------------------------------------------------------
   9. PRECIO_MERCADO (HU-07)
   ------------------------------------------------------------ */
CREATE TABLE precio_mercado (
    id_precio       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cultivo      INT NOT NULL,
    precio_por_kg   DECIMAL(6,2) NOT NULL,
    fecha_precio    DATE NOT NULL,
    CONSTRAINT uq_precio UNIQUE (id_cultivo, fecha_precio),
    CONSTRAINT fk_precio_cultivo FOREIGN KEY (id_cultivo)
        REFERENCES cultivo(id_cultivo) ON DELETE CASCADE
);
/* ------------------------------------------------------------
   10. NOTIFICACION (HU-08)
   ------------------------------------------------------------ */
CREATE TABLE notificacion (
    id_notificacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario      INT NOT NULL,
    titulo          VARCHAR(150) NOT NULL,
    mensaje         VARCHAR(500) NOT NULL,
    leida           BOOLEAN NOT NULL DEFAULT FALSE,
    fecha_creacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notificacion_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario) ON DELETE CASCADE
);
/* ------------------------------------------------------------
   11. GASTO_VIAJE (HU-20)
   Antes apuntaba a viaje; ahora apunta a lote.
   ------------------------------------------------------------ */
CREATE TABLE gasto_viaje (
    id_gasto        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_lote         INT NOT NULL,
    concepto        VARCHAR(100) NOT NULL,
    monto           DECIMAL(10,2) NOT NULL CHECK (monto > 0),
    fecha_hora      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_gasto_lote FOREIGN KEY (id_lote)
        REFERENCES lote(id_lote) ON DELETE CASCADE
);
-- Verificacion: deben aparecer 11 tablas
SELECT COUNT(*) AS total_tablas FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
