spring.application.name=AgroDirectoAPI
server.port=8088

spring.datasource.url=jdbc:postgresql://localhost:5432/agrodirecto
spring.datasource.username=postgres
spring.datasource.password=postgre
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
app.jwt.secret=${JWT_SECRET:AgroDirectoJWTSecretKey2026-UPC-Proyecto-Backend-Seguridad}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}

logging.level.root=INFO
logging.file.name=logs/log_agrodirecto.log
